[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  path = "/*"
  function = "rewrite"

[[redirects]]
  from = "/*"
  to = "/_ipx"
  status = 200
  force = true
  conditions = {Referer = ["/_next/image*"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 