export interface Trade {
  id: string;
  accountId?: string;
  symbol: string;
  direction: 'long' | 'short';
  quantity: number;
  entryPrice: number;
  entryDate: string;
  exitPrice?: number;
  exitDate?: string;
  pnl?: number;
  fees?: number;
  strategy?: string;
  emotionalState?: string;
  notes?: string;
  tags?: string[];
  source?: string;
  importSource?: string;
  contractMultiplier?: number;
  preMarketNotes?: string;
  riskRewardRatio?: string;
  stopLoss?: number;
  takeProfit?: number;
  mistakes?: string;
  lessonLearned?: string;
  tradeSetup?: string;
  marketCondition?: string;
  maxAdverseExcursion?: number;
  maxFavorableExcursion?: number;
} 