name: Setup Trading Journal Project

on:
  workflow_dispatch:
  
permissions:
  contents: read
  issues: write

jobs:
  setup-project:
    runs-on: ubuntu-latest
    steps:
      - name: List issues and suggest project setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking created issues..."
          
          # List all issues that start with [W
          echo "=== Trading Journal Issues ==="
          gh issue list --limit 100 --json number,title,labels --jq '.[] | select(.title | startswith("[W")) | "Issue #\(.number): \(.title) - Labels: \(.labels | map(.name) | join(", "))"'
          
          echo ""
          echo "=== Manual Project Setup Instructions ==="
          echo "1. Go to https://github.com/${{ github.repository }}/projects"
          echo "2. Click 'New project'"
          echo "3. Choose 'Board' template"
          echo "4. Name it 'Trading Journal Development'"
          echo "5. Add the issues above to organize your development workflow"
          echo ""
          echo "Or use GitHub's built-in project features:"
          echo "- Go to Issues tab"
          echo "- Use Milestones for each week"
          echo "- Use Labels to filter by category (API, UI, Database, etc.)"
          echo "- Use Assignees to track ownership"
